# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: deploy blog (only on push to main branch)
on:
  push:
    branches: main
# Declare default permissions as read only.
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      # Need to be able to write to the deploy branch
      contents: write
    steps:
    - name: checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0  # need to fetch all history to ensure correct Git revision dates in docs

    - name: set up Python
      uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: '3.13'

    - name: install mkdocs + plugins
      run: |
          pip install -r requirements.txt
          pip list | grep mkdocs
          mkdocs --version

    - name: build blog
      run: make test && make deploy
